version: "3.9"

services:
  db:
    image: postgres:15
    container_name: "database"
    ports:
      - '5440:5432'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres