// Code generated by MockGen. DO NOT EDIT.
// Source: domain/contact.go
//
// Generated by this command:
//
//	mockgen -source=domain/contact.go -destination=mocks/contact.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "ppo/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIContactsRepository is a mock of IContactsRepository interface.
type MockIContactsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIContactsRepositoryMockRecorder
}

// MockIContactsRepositoryMockRecorder is the mock recorder for MockIContactsRepository.
type MockIContactsRepositoryMockRecorder struct {
	mock *MockIContactsRepository
}

// NewMockIContactsRepository creates a new mock instance.
func NewMockIContactsRepository(ctrl *gomock.Controller) *MockIContactsRepository {
	mock := &MockIContactsRepository{ctrl: ctrl}
	mock.recorder = &MockIContactsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContactsRepository) EXPECT() *MockIContactsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIContactsRepository) Create(arg0 context.Context, arg1 *domain.Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIContactsRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIContactsRepository)(nil).Create), arg0, arg1)
}

// DeleteById mocks base method.
func (m *MockIContactsRepository) DeleteById(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockIContactsRepositoryMockRecorder) DeleteById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockIContactsRepository)(nil).DeleteById), arg0, arg1)
}

// GetById mocks base method.
func (m *MockIContactsRepository) GetById(arg0 context.Context, arg1 uuid.UUID) (*domain.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(*domain.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIContactsRepositoryMockRecorder) GetById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIContactsRepository)(nil).GetById), arg0, arg1)
}

// GetByOwnerId mocks base method.
func (m *MockIContactsRepository) GetByOwnerId(arg0 context.Context, arg1 uuid.UUID, arg2 int, arg3 bool) ([]*domain.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwnerId", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOwnerId indicates an expected call of GetByOwnerId.
func (mr *MockIContactsRepositoryMockRecorder) GetByOwnerId(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwnerId", reflect.TypeOf((*MockIContactsRepository)(nil).GetByOwnerId), arg0, arg1, arg2, arg3)
}

// Update mocks base method.
func (m *MockIContactsRepository) Update(arg0 context.Context, arg1 *domain.Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIContactsRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIContactsRepository)(nil).Update), arg0, arg1)
}

// MockIContactsService is a mock of IContactsService interface.
type MockIContactsService struct {
	ctrl     *gomock.Controller
	recorder *MockIContactsServiceMockRecorder
}

// MockIContactsServiceMockRecorder is the mock recorder for MockIContactsService.
type MockIContactsServiceMockRecorder struct {
	mock *MockIContactsService
}

// NewMockIContactsService creates a new mock instance.
func NewMockIContactsService(ctrl *gomock.Controller) *MockIContactsService {
	mock := &MockIContactsService{ctrl: ctrl}
	mock.recorder = &MockIContactsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContactsService) EXPECT() *MockIContactsServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIContactsService) Create(arg0 context.Context, arg1 *domain.Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIContactsServiceMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIContactsService)(nil).Create), arg0, arg1)
}

// DeleteById mocks base method.
func (m *MockIContactsService) DeleteById(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockIContactsServiceMockRecorder) DeleteById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockIContactsService)(nil).DeleteById), arg0, arg1)
}

// GetById mocks base method.
func (m *MockIContactsService) GetById(arg0 context.Context, arg1 uuid.UUID) (*domain.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(*domain.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIContactsServiceMockRecorder) GetById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIContactsService)(nil).GetById), arg0, arg1)
}

// GetByOwnerId mocks base method.
func (m *MockIContactsService) GetByOwnerId(arg0 context.Context, arg1 uuid.UUID, arg2 int, arg3 bool) ([]*domain.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwnerId", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOwnerId indicates an expected call of GetByOwnerId.
func (mr *MockIContactsServiceMockRecorder) GetByOwnerId(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwnerId", reflect.TypeOf((*MockIContactsService)(nil).GetByOwnerId), arg0, arg1, arg2, arg3)
}

// Update mocks base method.
func (m *MockIContactsService) Update(arg0 context.Context, arg1 *domain.Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIContactsServiceMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIContactsService)(nil).Update), arg0, arg1)
}
