// Code generated by MockGen. DO NOT EDIT.
// Source: domain/skill.go
//
// Generated by this command:
//
//	mockgen -source=domain/skill.go -destination=mocks/skill.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "ppo/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockISkillRepository is a mock of ISkillRepository interface.
type MockISkillRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISkillRepositoryMockRecorder
}

// MockISkillRepositoryMockRecorder is the mock recorder for MockISkillRepository.
type MockISkillRepositoryMockRecorder struct {
	mock *MockISkillRepository
}

// NewMockISkillRepository creates a new mock instance.
func NewMockISkillRepository(ctrl *gomock.Controller) *MockISkillRepository {
	mock := &MockISkillRepository{ctrl: ctrl}
	mock.recorder = &MockISkillRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISkillRepository) EXPECT() *MockISkillRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockISkillRepository) Create(arg0 context.Context, arg1 *domain.Skill) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockISkillRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockISkillRepository)(nil).Create), arg0, arg1)
}

// DeleteById mocks base method.
func (m *MockISkillRepository) DeleteById(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockISkillRepositoryMockRecorder) DeleteById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockISkillRepository)(nil).DeleteById), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockISkillRepository) GetAll(arg0 context.Context, arg1 int) ([]*domain.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockISkillRepositoryMockRecorder) GetAll(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockISkillRepository)(nil).GetAll), arg0, arg1)
}

// GetById mocks base method.
func (m *MockISkillRepository) GetById(arg0 context.Context, arg1 uuid.UUID) (*domain.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(*domain.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockISkillRepositoryMockRecorder) GetById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockISkillRepository)(nil).GetById), arg0, arg1)
}

// Update mocks base method.
func (m *MockISkillRepository) Update(arg0 context.Context, arg1 *domain.Skill) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockISkillRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockISkillRepository)(nil).Update), arg0, arg1)
}

// MockISkillService is a mock of ISkillService interface.
type MockISkillService struct {
	ctrl     *gomock.Controller
	recorder *MockISkillServiceMockRecorder
}

// MockISkillServiceMockRecorder is the mock recorder for MockISkillService.
type MockISkillServiceMockRecorder struct {
	mock *MockISkillService
}

// NewMockISkillService creates a new mock instance.
func NewMockISkillService(ctrl *gomock.Controller) *MockISkillService {
	mock := &MockISkillService{ctrl: ctrl}
	mock.recorder = &MockISkillServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISkillService) EXPECT() *MockISkillServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockISkillService) Create(arg0 context.Context, arg1 *domain.Skill) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockISkillServiceMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockISkillService)(nil).Create), arg0, arg1)
}

// DeleteById mocks base method.
func (m *MockISkillService) DeleteById(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockISkillServiceMockRecorder) DeleteById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockISkillService)(nil).DeleteById), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockISkillService) GetAll(arg0 context.Context, arg1 int) ([]*domain.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockISkillServiceMockRecorder) GetAll(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockISkillService)(nil).GetAll), arg0, arg1)
}

// GetById mocks base method.
func (m *MockISkillService) GetById(arg0 context.Context, arg1 uuid.UUID) (*domain.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(*domain.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockISkillServiceMockRecorder) GetById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockISkillService)(nil).GetById), arg0, arg1)
}

// Update mocks base method.
func (m *MockISkillService) Update(arg0 context.Context, arg1 *domain.Skill) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockISkillServiceMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockISkillService)(nil).Update), arg0, arg1)
}
