// Code generated by MockGen. DO NOT EDIT.
// Source: fin_report.go
//
// Generated by this command:
//
//	mockgen -source=fin_report.go -destination=mocks/fin_report.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "business-logic/domain"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIFinancialReportRepository is a mock of IFinancialReportRepository interface.
type MockIFinancialReportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIFinancialReportRepositoryMockRecorder
}

// MockIFinancialReportRepositoryMockRecorder is the mock recorder for MockIFinancialReportRepository.
type MockIFinancialReportRepositoryMockRecorder struct {
	mock *MockIFinancialReportRepository
}

// NewMockIFinancialReportRepository creates a new mock instance.
func NewMockIFinancialReportRepository(ctrl *gomock.Controller) *MockIFinancialReportRepository {
	mock := &MockIFinancialReportRepository{ctrl: ctrl}
	mock.recorder = &MockIFinancialReportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFinancialReportRepository) EXPECT() *MockIFinancialReportRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIFinancialReportRepository) Create(ctx context.Context, finRep *domain.FinancialReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, finRep)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIFinancialReportRepositoryMockRecorder) Create(ctx, finRep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIFinancialReportRepository)(nil).Create), ctx, finRep)
}

// DeleteById mocks base method.
func (m *MockIFinancialReportRepository) DeleteById(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockIFinancialReportRepositoryMockRecorder) DeleteById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockIFinancialReportRepository)(nil).DeleteById), ctx, id)
}

// GetByCompany mocks base method.
func (m *MockIFinancialReportRepository) GetByCompany(ctx context.Context, companyId uuid.UUID, period *domain.Period) (*domain.FinancialReportByPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCompany", ctx, companyId, period)
	ret0, _ := ret[0].(*domain.FinancialReportByPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCompany indicates an expected call of GetByCompany.
func (mr *MockIFinancialReportRepositoryMockRecorder) GetByCompany(ctx, companyId, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCompany", reflect.TypeOf((*MockIFinancialReportRepository)(nil).GetByCompany), ctx, companyId, period)
}

// GetById mocks base method.
func (m *MockIFinancialReportRepository) GetById(ctx context.Context, id uuid.UUID) (*domain.FinancialReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(*domain.FinancialReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIFinancialReportRepositoryMockRecorder) GetById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIFinancialReportRepository)(nil).GetById), ctx, id)
}

// Update mocks base method.
func (m *MockIFinancialReportRepository) Update(ctx context.Context, finRep *domain.FinancialReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, finRep)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIFinancialReportRepositoryMockRecorder) Update(ctx, finRep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIFinancialReportRepository)(nil).Update), ctx, finRep)
}

// MockIFinancialReportService is a mock of IFinancialReportService interface.
type MockIFinancialReportService struct {
	ctrl     *gomock.Controller
	recorder *MockIFinancialReportServiceMockRecorder
}

// MockIFinancialReportServiceMockRecorder is the mock recorder for MockIFinancialReportService.
type MockIFinancialReportServiceMockRecorder struct {
	mock *MockIFinancialReportService
}

// NewMockIFinancialReportService creates a new mock instance.
func NewMockIFinancialReportService(ctrl *gomock.Controller) *MockIFinancialReportService {
	mock := &MockIFinancialReportService{ctrl: ctrl}
	mock.recorder = &MockIFinancialReportServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFinancialReportService) EXPECT() *MockIFinancialReportServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIFinancialReportService) Create(finRep *domain.FinancialReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", finRep)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIFinancialReportServiceMockRecorder) Create(finRep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIFinancialReportService)(nil).Create), finRep)
}

// CreateByPeriod mocks base method.
func (m *MockIFinancialReportService) CreateByPeriod(finReportByPeriod *domain.FinancialReportByPeriod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateByPeriod", finReportByPeriod)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateByPeriod indicates an expected call of CreateByPeriod.
func (mr *MockIFinancialReportServiceMockRecorder) CreateByPeriod(finReportByPeriod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateByPeriod", reflect.TypeOf((*MockIFinancialReportService)(nil).CreateByPeriod), finReportByPeriod)
}

// DeleteById mocks base method.
func (m *MockIFinancialReportService) DeleteById(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockIFinancialReportServiceMockRecorder) DeleteById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockIFinancialReportService)(nil).DeleteById), id)
}

// GetByCompany mocks base method.
func (m *MockIFinancialReportService) GetByCompany(companyId uuid.UUID, period *domain.Period) (*domain.FinancialReportByPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCompany", companyId, period)
	ret0, _ := ret[0].(*domain.FinancialReportByPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCompany indicates an expected call of GetByCompany.
func (mr *MockIFinancialReportServiceMockRecorder) GetByCompany(companyId, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCompany", reflect.TypeOf((*MockIFinancialReportService)(nil).GetByCompany), companyId, period)
}

// GetById mocks base method.
func (m *MockIFinancialReportService) GetById(id uuid.UUID) (*domain.FinancialReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(*domain.FinancialReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIFinancialReportServiceMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIFinancialReportService)(nil).GetById), id)
}

// Update mocks base method.
func (m *MockIFinancialReportService) Update(finRep *domain.FinancialReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", finRep)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIFinancialReportServiceMockRecorder) Update(finRep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIFinancialReportService)(nil).Update), finRep)
}
